"""Constants for the Cudy Router integration."""

DOMAIN = "hass_cudy_router"

MODULE_INFO = "info"
MODULE_DEVICES = "devices"
MODULE_MESH = "mesh"
MODULE_LAN = "lan"
MODULE_WAN = "wan"
MODULE_WIRELESS_24G = "24g_wireless"
MODULE_WIRELESS_5G = "5g_wireless"
MODULE_SYSTEM = "system"
MODULE_DHCP = "dhcp"
MODULE_GSM = "gsm"
MODULE_SMS = "SMS"

SECTION_DETAILED = "detailed"

OPTIONS_DEVICE_LIST = "device_list"

## Info
SENSOR_INFO_WORK_MODE = "info_work_mode"
SENSOR_INFO_INTERFACE = "info_interface"
## System
SENSOR_SYSTEM_FIRMWARE_VERSION = "system_firmware_version"
SENSOR_SYSTEM_HARDWARE = "system_hardware"
SENSOR_SYSTEM_UPTIME = "system_uptime"
SENSOR_SYSTEM_LOCALTIME = "system_localtime"
## Mesh
SENSOR_MESH_NETWORK = "mesh_network"
SENSOR_MESH_UNITS = "mesh_units"
## WAN
SENSOR_WAN_PUBLIC_IP = "wan_public_ip"
SENSOR_WAN_IP = "wan_ip"
SENSOR_WAN_DNS = "wan_dns"
SENSOR_WAN_TYPE = "wan_type"
SENSOR_WAN_GATEWAY = "wan_gateway"
SENSOR_WAN_UPTIME = "wan_uptime"
## LAN
SENSOR_LAN_IP = "lan_ip"
SENSOR_LAN_SUBNET = "lan_subnet"
SENSOR_LAN_MAC = "lan_mac"
## WiFI 2.4G
SENSOR_24G_WIFI_SSID = "24g_wifi_ssid"
SENSOR_24G_WIFI_BSSID = "24g_wifi_bssid"
SENSOR_24G_WIFI_ENCRYPTION = "24g_wifi_encryption"
SENSOR_24G_WIFI_CHANNEL = "24g_wifi_channel"
## WiFi 5G
SENSOR_5G_WIFI_SSID = "5g_wifi_ssid"
SENSOR_5G_WIFI_BSSID = "5g_wifi_bssid"
SENSOR_5G_WIFI_ENCRYPTION = "5g_wifi_encryption"
SENSOR_5G_WIFI_CHANNEL = "5g_wifi_channel"
## Devices
SENSOR_DEVICE_COUNT = "device_count"
SENSOR_WIFI_24_DEVICE_COUNT = "device_wifi_24_device_count"
SENSOR_WIFI_5_DEVICE_COUNT = "device_wifi_5_device_count"
SENSOR_WIRED_DEVICE_COUNT = "device_wired_device_count"
SENSOR_MESH_DEVICE_COUNT = "device_mesh_device_count"
SENSOR_DEVICE_ONLINE = "device_online"
SENSOR_DEVICE_BLOCKED = "device_blocked"
## DHCP
SENSOR_DHCP_IP_START = "dhcp_ip_start"
SENSOR_DHCP_IP_END = "dhcp_ip_end"
SENSOR_DHCP_DNS_PRIMARY = "dhcp_dns_primary"
SENSOR_DHCP_DNS_SECONDARY = "device_dns_secondary"
SENSOR_DHCP_GATEWAY = "device_gateway"
SENSOR_DHCP_LEASE_TIME = "device_lease_time"
## GSM
SENSOR_GSM_NETWORK_TYPE = "gsm_network_type"
SENSOR_GSM_DOWNLOAD = "gsm_download"
SENSOR_GSM_UPLOAD = "gsm_upload"
SENSOR_GSM_PUBLIC_IP = "gsm_public_ip"
SENSOR_GSM_IP_ADDRESS = "gsm_ip_address"
SENSOR_GSM_CONNECTED_TIME = "gsm_connected_time"
## SMS
SENSOR_SMS_INBOX = "sms_inbox"
SENSOR_SMS_OUTBOX = "sms_outbox"

DEVICE_HOSTNAME = "hostname"
DEVICE_IP = "ip"
DEVICE_MAC = "mac"
DEVICE_UPLOAD_SPEED = "upload_speed"
DEVICE_DOWNLOAD_SPEED = "download_speed"
DEVICE_SIGNAL = "signal"
DEVICE_ONLINE_TIME = "online_time"
DEVICE_CONNECTION_TYPE = "connection_type"


ICON_INFO_WORK_MODE = "mdi:router-wireless"
ICON_INFO_INTERFACE = "mdi:router-network"
ICON_FIRMWARE_VERSION = "mdi:numeric"
ICON_HARDWARE = "mdi:chip"
ICON_SYSTEM_UPTIME = "mdi:clock-check"
ICON_SYSTEM_LOCALTIME = "mdi:clock-check"
ICON_MESH_NETWORK = "mdi:table-network"
ICON_MESH_UNITS = "mdi:server-network"
ICON_WAN_PUBLIC_IP = "mdi:web"
ICON_WAN_IP = "mdi:ip-network"
ICON_WAN_DNS = "mdi:dns"
ICON_WAN_TYPE = "mdi:transit-connection-variant"
ICON_WAN_GATEWAY = "mdi:gate-open"
ICON_WAN_UPTIME = "mdi:clock-check"
ICON_LAN_IP = "mdi:lan"
ICON_LAN_SUBNET = "mdi:network"
ICON_LAN_MAC = "mdi:network-pos"
ICON_DEVICE_COUNT = "mdi:devices"
ICON_WIFI_24_DEVICE_COUNT = "mdi:wifi"
ICON_WIFI_5_DEVICE_COUNT = "mdi:wifi-star"
ICON_WIRED_DEVICE_COUNT = "mdi:connection"
ICON_MESH_DEVICE_COUNT = "mdi:table-network"
ICON_DEVICE_ONLINE = "mdi:network"
ICON_DEVICE_BLOCKED = "mdi:network-off"
ICON_DHCP_IP_START = "mdi:ray-start-arrow"
ICON_DHCP_IP_END = "mdi:ray-end-arrow"
ICON_DHCP_DNS_PRIMARY = "mdi:dns"
ICON_DHCP_DNS_SECONDARY = "mdi:dns-outline"
ICON_DHCP_GATEWAY = "mdi:gate-open"
ICON_DHCP_LEASE_TIME = "mdi:clock-time-seven"
ICON_GSM_NETWORK_TYPE = "mdi:transit-connection-variant"
ICON_GSM_DOWNLOAD = "mdi:download"
ICON_GSM_UPLOAD = "mdi:upload"
ICON_GSM_PUBLIC_IP = "mdi:web"
ICON_GSM_IP_ADDRESS = "mdi:ip-network"
ICON_GSM_CONNECTED_TIME = "mdi:clock-check"
ICON_SMS_INBOX = "mdi:inbox-arrow-down"
ICON_SMS_OUTBOX = "mdi:inbox-arrow-up"