"""Constants for the Cudy Router integration."""

DOMAIN = "hass_cudy_router"

MODULE_DEVICES = "devices"
MODULE_MESH = "mesh"
MODULE_LAN = "lan"
MODULE_WAN = "wan"
MODULE_SYSTEM = "system"

SECTION_DETAILED = "detailed"

OPTIONS_DEVICELIST = "device_list"

SENSOR_FIRMWARE_VERSION = "firmware_version"
SENSOR_HARDWARE = "hardware"
SENSOR_SYSTEM_UPTIME = "system_uptime"
SENSOR_MESH_NETWORK = "mesh_network"
SENSOR_MESH_UNITS = "mesh_units"
SENSOR_WAN_PUBLIC_IP = "wan_public_ip"
SENSOR_WAN_IP = "wan_ip"
SENSOR_WAN_DNS = "wan_dns"
SENSOR_WAN_TYPE = "wan_type"
SENSOR_WAN_UPTIME = "wan_uptime"
SENSOR_LAN_IP = "lan_ip"
SENSOR_DEVICE_COUNT = "device_count"
SENSOR_WIFI_24_DEVICE_COUNT = "wifi_24_device_count"
SENSOR_WIFI_5_DEVICE_COUNT = "wifi_5_device_count"
SENSOR_WIRED_DEVICE_COUNT = "wired_device_count"
SENSOR_MESH_DEVICE_COUNT = "mesh_device_count"

DEVICE_HOSTNAME = "hostname"
DEVICE_IP = "ip"
DEVICE_MAC = "mac"
DEVICE_UPLOAD_SPEED = "upload_speed"
DEVICE_DOWNLOAD_SPEED = "download_speed"
DEVICE_SIGNAL = "signal"
DEVICE_ONLINE_TIME = "online_time"
DEVICE_CONNECTION = "connection"
DEVICE_CONNECTION_TYPE = "connection_type"