"""Constants for the Cudy Router integration."""

DOMAIN = "hass_cudy_router"

MODULE_DEVICES = "devices"
MODULE_MESH = "mesh"
MODULE_LAN = "lan"
MODULE_WAN = "wan"
MODULE_SYSTEM = "system"
MODULE_DHCP = "dhcp"

SECTION_DETAILED = "detailed"

OPTIONS_DEVICE_LIST = "device_list"

SENSOR_FIRMWARE_VERSION = "system_firmware_version"
SENSOR_HARDWARE = "system_hardware"
SENSOR_SYSTEM_UPTIME = "system_uptime"
SENSOR_SYSTEM_LOCALTIME = "system_localtime"
SENSOR_MESH_NETWORK = "mesh_network"
SENSOR_MESH_UNITS = "mesh_units"
SENSOR_WAN_PUBLIC_IP = "wan_public_ip"
SENSOR_WAN_IP = "wan_ip"
SENSOR_WAN_DNS = "wan_dns"
SENSOR_WAN_TYPE = "wan_type"
SENSOR_WAN_GATEWAY = "wan_gateway"
SENSOR_WAN_UPTIME = "wan_uptime"
SENSOR_LAN_IP = "lan_ip"
SENSOR_LAN_SUBNET = "lan_subnet"
SENSOR_LAN_MAC = "lan_mac"
SENSOR_DEVICE_COUNT = "device_count"
SENSOR_WIFI_24_DEVICE_COUNT = "device_wifi_24_device_count"
SENSOR_WIFI_5_DEVICE_COUNT = "device_wifi_5_device_count"
SENSOR_WIRED_DEVICE_COUNT = "device_wired_device_count"
SENSOR_MESH_DEVICE_COUNT = "device_mesh_device_count"
SENSOR_DEVICE_ONLINE = "device_online"
SENSOR_DEVICE_BLOCKED = "device_blocked"
SENSOR_DHCP_IP_START = "dhcp_ip_start"
SENSOR_DHCP_IP_END = "dhcp_ip_end"
SENSOR_DHCP_DNS_PRIMARY = "dhcp_dns_primary"
SENSOR_DHCP_DNS_SECONDARY = "device_dns_secondary"
SENSOR_DHCP_GATEWAY = "device_gateway"
SENSOR_DHCP_LEASE_TIME = "device_lease_time"

DEVICE_HOSTNAME = "hostname"
DEVICE_IP = "ip"
DEVICE_MAC = "mac"
DEVICE_UPLOAD_SPEED = "upload_speed"
DEVICE_DOWNLOAD_SPEED = "download_speed"
DEVICE_SIGNAL = "signal"
DEVICE_ONLINE_TIME = "online_time"
DEVICE_CONNECTION = "connection"
DEVICE_CONNECTION_TYPE = "connection_type"


ICON_FIRMWARE_VERSION = "mdi:numeric"
ICON_HARDWARE = "mdi:chip"
ICON_SYSTEM_UPTIME = "mdi:clock-check"
ICON_SYSTEM_LOCALTIME = "mdi:clock-check"
ICON_MESH_NETWORK = "mdi:table-network"
ICON_MESH_UNITS = "mdi:server-network"
ICON_WAN_PUBLIC_IP = "mdi:web"
ICON_WAN_IP = "mdi:ip-network"
ICON_WAN_DNS = "mdi:dns"
ICON_WAN_TYPE = "mdi:transit-connection-variant"
ICON_WAN_GATEWAY = "mdi:gate-open"
ICON_WAN_UPTIME = "mdi:clock-check"
ICON_LAN_IP = "mdi:lan"
ICON_LAN_SUBNET = "mdi:network"
ICON_LAN_MAC = "mdi:network-pos"
ICON_DEVICE_COUNT = "mdi:devices"
ICON_WIFI_24_DEVICE_COUNT = "mdi:wifi"
ICON_WIFI_5_DEVICE_COUNT = "mdi:wifi-star"
ICON_WIRED_DEVICE_COUNT = "mdi:connection"
ICON_MESH_DEVICE_COUNT = "mdi:table-network"
ICON_DEVICE_ONLINE = "mdi:network"
ICON_DEVICE_BLOCKED = "mdi:network-off"
ICON_DHCP_IP_START = "mdi:ray-start-arrow"
ICON_DHCP_IP_END = "mdi:ray-end-arrow"
ICON_DHCP_DNS_PRIMARY = "mdi:dns"
ICON_DHCP_DNS_SECONDARY = "mdi:dns-outline"
ICON_DHCP_GATEWAY = "mdi:gate-open"
ICON_DHCP_LEASE_TIME = "mdi:clock-time-seven"